#!/usr/bin/env python3
"""从 data/areas.json 生成三语言 data 文件，支持 --check 模式"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = ROOT / "data" / "areas.json"

TS_OUT = ROOT / "packages" / "typescript" / "src" / "data.ts"
PY_OUT = ROOT / "packages" / "python" / "src" / "cn_area" / "_data.py"
GO_OUT = ROOT / "packages" / "go" / "data.go"


def load_data() -> list[dict]:
    with open(JSON_PATH, encoding="utf-8") as f:
        return json.load(f)


def _json_node(node: dict, indent: int) -> str:
    """递归生成单个节点的 JSON 字符串"""
    parts = ['"code":"' + node["code"] + '"']
    parts.append('"name":"' + node["name"] + '"')
    parts.append('"type":"' + node["type"] + '"')
    children = node.get("children")
    if children:
        child_strs = [_json_node(c, indent + 1) for c in children]
        inner = (",\n" + "  " * (indent + 1)).join(child_strs)
        parts.append('"children":[\n' + "  " * (indent + 1) + inner + "\n" + "  " * indent + "]")
    return "{" + ", ".join(parts) + "}"


# ── TypeScript ──────────────────────────────────────────────────────────────

def gen_typescript(data: list[dict]) -> str:
    nodes = []
    for prov in data:
        nodes.append(_json_node(prov, 1))
    body = ",\n  ".join(nodes)
    return (
        '// This file is auto-generated by scripts/generate.py — DO NOT EDIT\n'
        'export interface AreaNode {\n'
        '  code: string;\n'
        '  name: string;\n'
        '  type: string;\n'
        '  children?: AreaNode[];\n'
        '}\n'
        '\n'
        'export const areas: AreaNode[] = [\n'
        '  ' + body + '\n'
        '];\n'
    )


# ── Python ──────────────────────────────────────────────────────────────────

def _py_node(node: dict, indent: int) -> str:
    pad = "    " * indent
    parts = [f'"code": "{node["code"]}"', f'"name": "{node["name"]}"', f'"type": "{node["type"]}"']
    children = node.get("children")
    if children:
        child_strs = [_py_node(c, indent + 1) for c in children]
        inner = ",\n".join(child_strs)
        parts.append('"children": [\n' + inner + "\n" + pad + "]")
    return pad + "{" + ", ".join(parts) + "}"


def gen_python(data: list[dict]) -> str:
    nodes = [_py_node(prov, 1) for prov in data]
    body = ",\n".join(nodes)
    return (
        '# This file is auto-generated by scripts/generate.py — DO NOT EDIT\n'
        'from __future__ import annotations\n'
        '\n'
        'AREAS: list[dict] = [\n'
        + body + '\n'
        ']\n'
    )


# ── Go ──────────────────────────────────────────────────────────────────────

def _go_node(node: dict, indent: int, is_city: bool = False) -> str:
    pad = "\t" * indent
    parts = [f'Code: "{node["code"]}"', f'Name: "{node["name"]}"', f'Type: "{node["type"]}"']
    children = node.get("children")
    if children:
        field = "Districts" if is_city else "Cities"
        type_name = "District" if is_city else "City"
        child_strs = [_go_node(c, indent + 1, is_city=True) for c in children]
        inner = "\n".join(child_strs)
        parts.append(f'{field}: []{type_name}{{\n' + inner + "\n" + pad + "}")
    return pad + "{" + ", ".join(parts) + "},"


def gen_go(data: list[dict]) -> str:
    nodes = [_go_node(prov, 1) for prov in data]
    body = "\n".join(nodes)
    return (
        '// This file is auto-generated by scripts/generate.py — DO NOT EDIT\n'
        'package cnarea\n'
        '\n'
        'var areas = []Province{\n'
        + body + '\n'
        '}\n'
    )


# ── Main ────────────────────────────────────────────────────────────────────

def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        if not path.exists():
            print(f"  MISSING: {path.relative_to(ROOT)}")
            return False
        existing = path.read_text(encoding="utf-8")
        if existing != content:
            print(f"  DIFF: {path.relative_to(ROOT)}")
            return False
        print(f"  OK: {path.relative_to(ROOT)}")
        return True
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  Wrote: {path.relative_to(ROOT)}")
        return True


def main():
    check = "--check" in sys.argv
    data = load_data()

    ts_content = gen_typescript(data)
    py_content = gen_python(data)
    go_content = gen_go(data)

    if check:
        print("Checking generated files...")
    else:
        print("Generating files...")

    ok = True
    ok &= write_or_check(TS_OUT, ts_content, check)
    ok &= write_or_check(PY_OUT, py_content, check)
    ok &= write_or_check(GO_OUT, go_content, check)

    if check and not ok:
        print("\nGenerated files are out of date. Run: uv run scripts/generate.py")
        sys.exit(1)

    print("Done.")


if __name__ == "__main__":
    main()
